name: Run Go Code on Schedule

on:
  schedule:
    - cron: "0 10 * * *"   # jeden Tag 12:00 UTC
  workflow_dispatch:       # erlaubt manuelles Ausf√ºhren

jobs:
  run-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Go script
        run: go run Mensabot.go
